version: '3.1'
services:
# Postgres database service
  db:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/sql/:/docker-entrypoint-initdb.d/
      - ./postgresql/csv/:/csv/

# Adminer service (for viewing database)
#  adminer:
#    image: adminer
#    container_name: database-viewer
#    restart: unless-stopped
#    ports:
#      - 8989:8080

# Spring Boot service
  spring-boot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - db