version: '3.1'
services:
# Postgres database service
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/sql/:/docker-entrypoint-initdb.d/
      - ./postgresql/csv/:/csv/

# Adminer service
  adminer:
    image: adminer
    container_name: database-viewer
    restart: unless-stopped
    ports:
      - 8989:8080